version: "3.9"

services:
  portainer:
    container_name: portainer
    hostname: docker.home
    image: portainer/portainer-ce:2.20.1
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt_data:/etc/letsencrypt:ro
    command:
      - "--http-disabled"
      - "--bind-https"
      - ":443"
      - "--sslcert"
      - "/etc/letsencrypt/live/home.snigji.com/fullchain.pem"
      - "--sslkey"
      - "/etc/letsencrypt/live/home.snigji.com/privkey.pem"
    networks:
      default:
        ipv4_address: 192.168.74.192

volumes:
  portainer_data:
    name: portainer_data
  letsencrypt_data:
    name: letsencrypt_data
    external: true

networks:
  default:
    name: homelab_ipvlan_l3
    external: true
