version: "3.9"

services:
  adguard_home:
    container_name: adguard_home
    image: adguard/adguardhome:v0.107.43
    restart: unless-stopped
    volumes:
      - adguard_data:/opt/adguardhome
      - /var/ssl/adguard.snigji.com:/cert
      - /var/ssl/ca/ca.crt.pem:/usr/local/share/ca-certificates/ca.crt
    networks:
      default:
        ipv4_address: 192.168.74.100

  bind9:
    container_name: bind9
    image: ubuntu/bind9:9.18-23.10_edge
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
      BIND9_USER: root
    volumes:
      - /home/joe/docker_config/bind9:/etc/bind
      - bind_cache:/var/cache/bind
      - bind_record:/var/lib/bind
    networks:
      default:
        ipv4_address: 192.168.74.101

volumes:
  adguard_data:
    name: adguard_data
  bind_cache:
    name: bind_cache
  bind_record:
    name: bind_record

networks:
  default:
    name: homelab
    external: true
