version: "3.9"

services:
  adguard_home:
    container_name: adguard_home
    hostname: adguard.home
    image: adguard/adguardhome:v0.107.48
    restart: unless-stopped
    volumes:
      - adguard_data:/opt/adguardhome
      - letsencrypt_data:/etc/letsencrypt:ro
    networks:
      default:
        ipv4_address: 192.168.74.200

  bind9:
    container_name: bind9
    hostname: bind9.home
    image: ubuntu/bind9:9.18-23.10_edge
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
      BIND9_USER: root
    volumes:
      - bind_config:/etc/bind
      - bind_cache:/var/cache/bind
      - bind_record:/var/lib/bind
    networks:
      default:
        ipv4_address: 192.168.74.201

volumes:
  adguard_data:
    name: adguard_data
  bind_cache:
    name: bind_cache
  bind_record:
    name: bind_record
  bind_config:
    name: bind_config
  letsencrypt_data:
    name: letsencrypt_data

networks:
  default:
    name: homelab_ipvlan_l3
    external: true
