version: "3.9"

services:
  nsupdate-ddns:
    container_name: nsupdate-ddns
    hostname: nsupdate-ddns
    labels:
      nl.mtak.docker-nsupdate-ddns.ignore: true
    image: macabrequinox/docker-nsupdate-ddns:latest
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
      DOMAIN: test.snigji.com
      IGNORE_LABEL: nl.mtak.docker-nsupdate-ddns.ignore
      HOSTNAME_LABEL: nl.mtak.docker-nsupdate-ddns.hostname
      DEFAULT_NETWORK: 192.168.74.0/24
      REFRESH_INTERVAL: 30
      ONE_SHOT: "False"
      NAMESERVER: "192.168.74.201"
      TSIG_NAME: test
    env_file: "stack.env" # TSIG_KEY env var comes from here
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 192.168.74.7
    
networks:
  default:
    name: homelab_ipvlan_l3
    external: true