version: "3.9"

services:
  nginx_proxy_manager:
    container_name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:2.11.1
    restart: unless-stopped
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt

    networks:
      default:
        ipv4_address: 192.168.74.102

networks:
  default:
    name: homelab
    external: true

volumes:
  nginx_proxy_manager_data:
    name: nginx_proxy_manager_data
  nginx_proxy_manager_letsencrypt:
    name: nginx_proxy_manager_letsencrypt