version: "3.9"

services:
  filebrowser:
    container_name: filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser:v2.27.0
    restart: unless-stopped
    volumes:
      - filebrowser_data:/data
      - /var/ssl/file.snigji.com:/var/ssl/cert
      - /var/ssl/ca/ca.crt.pem:/usr/local/share/ca-certificates/ca.crt
      # Mount more volume on /srv to edit
      - filebrowser_srv:/srv
      - bind_config:/srv/bind9
      - adguard_data:/srv/adguard
      - portainer_data:/srv/portainer
      - jellyfin_config:/srv/jellyfin
      - qbittorrent_config:/srv/qbittorrent
    command:
      - "-d"
      - "/data/database.db"
      - "-t"
      - "/var/ssl/cert/ssl.crt.pem"
      - "-k"
      - "/var/ssl/cert/ssl.key.pem"
      - "-p"
      - "443"
    healthcheck:
      test: ["NONE"]
    networks:
      default:
        ipv4_address: 192.168.74.193

volumes:
  bind_config:
    name: bind_config
    external: true
  adguard_data:
    name: adguard_data
    external: true
  portainer_data:
    name: portainer_data
    external: true
  jellyfin_config:
    name: jellyfin_config
    external: true
  qbittorrent_config:
    name: qbittorrent_config
    external: true
  filebrowser_data:
    name: filebrowser_data
  filebrowser_srv:
    name: filebrowser_srv

networks:
  default:
    name: homelab_ipvlan_l3
    external: true
