version: "3.9"

services:
  filebrowser:
    container_name: filebrowser
    hostname: file
    image: filebrowser/filebrowser:v2.27.0
    restart: unless-stopped
    volumes:
      - filebrowser_data:/data
      - letsencrypt_data:/etc/letsencrypt:ro
      # Mount more volume on /srv to edit
      - filebrowser_srv:/srv
      - bind_config:/srv/bind9
      - adguard_data:/srv/adguard
      - portainer_data:/srv/portainer
      - jellyfin_config:/srv/jellyfin
      - qbittorrent_config:/srv/qbittorrent
      - letsencrypt_data:/srv/letsencrypt_data:ro
    command:
      - "-d"
      - "/data/database.db"
      - "-t"
      - "/etc/letsencrypt/live/home.snigji.com/fullchain.pem"
      - "-k"
      - "/etc/letsencrypt/live/home.snigji.com/privkey.pem"
      - "-p"
      - "443"
    healthcheck:
      test: ["NONE"]
    networks:
      default:
        ipv4_address: 192.168.74.193

volumes:
  bind_config:
    name: bind_config
    external: true
  adguard_data:
    name: adguard_data
    external: true
  portainer_data:
    name: portainer_data
    external: true
  jellyfin_config:
    name: jellyfin_config
    external: true
  qbittorrent_config:
    name: qbittorrent_config
    external: true
  letsencrypt_data:
    name: letsencrypt_data
    external: true
  filebrowser_data:
    name: filebrowser_data
  filebrowser_srv:
    name: filebrowser_srv

networks:
  default:
    name: homelab_ipvlan_l3
    external: true
