version: "3.9"

services:
  samba:
    container_name: samba
    hostname: samba
    image: ghcr.io/servercontainers/samba:latest
    restart: always
    environment:
      MODEL: 'MacPro7,1'
      AVAHI_NAME: 'LOLDriveNetwork'

      SAMBA_CONF_LOG_LEVEL: 3

      WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
      NETBIOS_DISABLE: 1

      GROUP_family: 1073

      # docker run -ti --rm --entrypoint create-hash.sh ghcr.io/servercontainers/samba:latest
      ACCOUNT_joe: "joe:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:FF2B2E1BFE0F0BA9E5DAA224D2A98C4D:[U          ]:LCT-65B90279:"
      UID_joe: 1074
      GROUPS_joe: family

      SAMBA_VOLUME_CONFIG_public: |
        [Public]
          path=/shares/public
          valid users = joe
          guest ok = no
          read only = no
          browseable = yes
    volumes:
      - /etc/avahi/services/:/external/avahi
      # NAS Mount
      - samba_share:/shares/public
    networks:
      default:
        ipv4_address: 192.168.74.104

volumes:
  samba_share:
    name: samba_share

networks:
  default:
    name: homelab
    external: true
