version: '3.9'

services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin:10.8.13-1
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/nasty/share/media:/media
      - /var/ssl/media.snigji.com:/var/ssl/cert:ro
      - /var/ssl/ca/ca.crt.pem:/usr/local/share/ca-certificates/ca.crt:ro
    restart: unless-stopped
    healthcheck:
      test: ["NONE"]
    networks:
      default:
        ipv4_address: 192.168.74.195
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-4.6.3
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=443
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - /mnt/nasty/share/media:/downloads
      - /var/ssl/torrent.snigji.com:/var/ssl/cert:ro
      - /var/ssl/ca/ca.crt.pem:/usr/local/share/ca-certificates/ca.crt:ro
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.74.196

volumes:
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
  qbittorrent_config:
    name: qbittorrent_config

networks:
  default:
    name: homelab_ipvlan_l3
    external: true