version: '3.9'

services:
  jellyfin-openssl-init:
    container_name: jellyfin-openssl-init
    hostname: jellyfin-openssl-init.home
    image: alpine/openssl:latest
    working_dir: /var/ssl/cert
    volumes:
      - letsencrypt_data:/etc/letsencrypt:ro
      - jellyfin_ssl:/var/ssl/cert
    restart: no
    entrypoint:
      - openssl
    command:
      - pkcs12
      - -export
      - -out
      - ssl.p12
      - -passout
      - "pass:"
      - -in
      - /etc/letsencrypt/live/home.snigji.com/fullchain.pem
      - -inkey
      - /etc/letsencrypt/live/home.snigji.com/privkey.pem
    networks:
      default:
        ipv4_address: 192.168.74.3
  jellyfin:
    depends_on:
      jellyfin-openssl-init:
        condition: service_completed_successfully
    container_name: jellyfin
    hostname: media.home
    image: jellyfin/jellyfin:10.8.13-1
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/nasty/share/media:/media
      - jellyfin_ssl:/var/ssl/cert:ro
    restart: unless-stopped
    healthcheck:
      test: ["NONE"]
    networks:
      default:
        ipv4_address: 192.168.74.195
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-4.6.3
    container_name: qbittorrent
    hostname: torrent.home
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=443
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - /mnt/nasty/share/media:/downloads
      - letsencrypt_data:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.74.196

volumes:
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
  jellyfin_ssl:
    name: jellyfin_ssl
  qbittorrent_config:
    name: qbittorrent_config
  letsencrypt_data:
    name: letsencrypt_data
    external: true

networks:
  default:
    name: homelab_ipvlan_l3
    external: true