version: "3.9"

services:
  adguard_home:
    container_name: adguard_home
    image: adguard/adguardhome:v0.107.43
    restart: unless-stopped
    volumes:
      - adguard_data:/opt/adguardhome
      - /home/joe/.cert:/cert
    networks:
      default:
        ipv4_address: 192.168.74.100

volumes:
  adguard_data:
    name: adguard_data

networks:
  default:
    name: homelab
    external: true
